# Repo: templates/
# File: azure-pipelines.yml
parameters:
- name: environment
  type: object
  default: []
- name: namespace
  default: []
#- name: release
#  default: []
- name: app
  default: []
- name: coveragetest
  default: []
- name: multidockerfile
  default: []
- name: dockerfile-1
  default: []
- name: dockerfile-2
  default: []
- name: dockerfile-3
  default: []

stages:
- ${{ if contains(variables['Build.SourceBranchName'], 'dev') }}:
  - stage: Development
    jobs:
    - template: develop-build_new.yaml@templates
      parameters:
          environment: dev
          namespace: ${{ parameters.namespace }}
          release: dev-${{ parameters.app }}
          app: ${{ parameters.app }}
          stage: Development
          coveragetest: ${{ parameters.coveragetest }}
          multidockerfile: ${{ parameters.multidockerfile }}

- ${{ if contains(variables['Build.SourceBranchName'], 'release') }}:        
  - stage: Quality
    jobs:
    - template: develop-build_new.yaml@templates
      parameters:
          environment: qa
          namespace: ${{ parameters.namespace }}
          release: qa-${{ parameters.app }}
          app: ${{ parameters.app }}
          stage: Quality
        
  - stage: Production
    jobs:
    - template: develop-build_new.yaml@templates
      parameters:
          environment: prod
          namespace: ${{ parameters.namespace }}
          release: prod-${{ parameters.app }}
          app: ${{ parameters.app }}
          stage: Production
- ${{ if contains(variables['Build.SourceBranchName'], 'hotfix') }}:        
  - stage: Quality
    jobs:
    - template: develop-build_new.yaml@templates
      parameters:
          environment: qa
          namespace: ${{ parameters.namespace }}
          release: qa-${{ parameters.app }}
          app: ${{ parameters.app }}
          stage: Quality
        
  - stage: Production
    jobs:
    - template: develop-build_new.yaml@templates
      parameters:
          environment: prod
          namespace: ${{ parameters.namespace }}
          release: prod-${{ parameters.app }}
          app: ${{ parameters.app }}
          stage: Production