# Repo: templates/
# File: azure-pipelines.yml
parameters:
- name: environment
  type: object
  default: []
- name: namespace
  default: []
- name: release
  default: []
- name: app
  default: []

resources:
  repositories:
    - repository: templates
      type: git
      name: Area-Engenharia/develop-build.yaml
      ref: refs/heads/dev
      
stages:
- stage: Development
  jobs:
  - template: BuildTemplates/develop-build.yaml@templates
    parameters:
        environment: []
        namespace: []
        release: []
        app: []

- stage: Quality
  jobs:
  - template: BuildTemplates/develop-build.yaml@templates
    parameters:
        environment: []
        namespace: []
        release: []
        app: []
        
- stage: Production
  jobs:
  - template: BuildTemplates/develop-build.yaml@templates
    parameters:
        environment: []
        namespace: []
        release: []
        app: []