# Repo: templates/
# File: azure-pipelines.yml
parameters:
- name: environment
  type: object
  default: []
- name: namespace
  default: []
- name: release
  default: []
- name: app
  default: []
    
stages:
- stage: Development
  jobs:
  - template: develop-build.yaml@templates
    parameters:
        environment: ${{ parameters.environment }}
        namespace: ${{ parameters.namespace }}
        release: ${{ parameters.release }}
        app: ${{ parameters.app }}
        
${{ if contains(variables['Build.SourceBranchName'], 'release') }}:
  environment: ${{ parameters.environment }}
- stage: Quality
  jobs:
  - template: develop-build.yaml@templates
    parameters:
        environment: ${{ parameters.environment }}
        namespace: ${{ parameters.namespace }}
        release: ${{ parameters.release }}
        app: ${{ parameters.app }}
        
- stage: Production
  jobs:
  - template: develop-build.yaml@templates
    parameters:
        environment: ${{ parameters.environment }}
        namespace: ${{ parameters.namespace }}
        release: ${{ parameters.release }}
        app: ${{ parameters.app }}