# Repo: templates/
# File: azure-pipelines.yml
parameters:
- name: environment
  type: object
  default: []
- name: namespace
  default: []
- name: release
  default: []
- name: app
  default: []
    
stages:
- stage: Development
  jobs:
  - template: develop-build.yaml@templates
    parameters:
        environment: ${{ paramenter.environment }}
        namespace: ${{ paramenter.namespace }}
        release: ${{ paramenter.release }}
        app: ${{ paramenter.app }}

- stage: Quality
  jobs:
  - template: develop-build.yaml@templates
    parameters:
        environment: []
        namespace: []
        release: []
        app: []
        
- stage: Production
  jobs:
  - template: BuildTemplates/develop-build.yaml@templates
    parameters:
        environment: []
        namespace: []
        release: []
        app: []