parameters:
- name: environment
  type: object
  default: []
- name: namespace
  default: []
- name: app
  default: []
- name: coveragetest
  type: boolean
  default: false
- name: deploymentconfig
  type: boolean
  default: false
- name: virtualservice
  type: boolean
  default: false
- name: autoscale
  type: boolean
  default: false
- name: nextjs
  type: boolean
  default: false
- name: variables
  type: string
  default: ''


stages:
- stage: Development
  ${{ if  parameters.variables }}:
    variables:
    - group: dev-${{ parameters.variables }}
  condition: contains(variables['Build.SourceBranch'], 'refs/heads/dev')
  jobs:
  - template: develop-build.yaml@templates
    parameters:
        environment: dev
        namespace: ${{ parameters.namespace }}
        release: dev-${{ parameters.app }}
        app: ${{ parameters.app }}
        stage: Development
        nextjs: ${{ parameters.nextjs }}
        deploymentconfig: ${{ parameters.deploymentconfig }}
        virtualservice: ${{ parameters.virtualservice }}
        coveragetest: ${{ parameters.coveragetest }}
        autoscale: ${{ parameters.autoscale }}
        variables: ${{ parameters.variables }}

#- ${{ if contains(variables['Build.SourceBranchName'], 'release*') }}:        
- stage: Quality
  ${{ if  parameters.variables }}:
    variables:
    - group: qa-${{ parameters.variables }}
  condition: or(contains(variables['Build.SourceBranch'], 'refs/heads/release'), contains(variables['Build.SourceBranch'], 'refs/heads/hotfix'))
  jobs:
  - template: develop-build.yaml@templates
    parameters:
        environment: qa
        namespace: ${{ parameters.namespace }}
        release: qa-${{ parameters.app }}
        app: ${{ parameters.app }}
        stage: Quality
        nextjs: ${{ parameters.nextjs }}
        deploymentconfig: ${{ parameters.deploymentconfig }}
        virtualservice: ${{ parameters.virtualservice }}
        coveragetest: ${{ parameters.coveragetest }}
        autoscale: ${{ parameters.autoscale }}
        variables: ${{ parameters.variables }}

- stage: Production
  ${{ if  parameters.variables }}:
    variables:
    - group: prod-${{ parameters.variables }}
  condition: or(succeeded(), contains(variables['Build.SourceBranch'], 'refs/heads/release'), contains(variables['Build.SourceBranch'], 'refs/heads/hotfix'))
  jobs:
  - template: develop-build.yaml@templates
    parameters:
        environment: prod
        namespace: ${{ parameters.namespace }}
        release: prod-${{ parameters.app }}
        app: ${{ parameters.app }}
        stage: Production
        nextjs: ${{ parameters.nextjs }}
        deploymentconfig: ${{ parameters.deploymentconfig }}
        virtualservice: ${{ parameters.virtualservice }}
        coveragetest: ${{ parameters.coveragetest }}
        autoscale: ${{ parameters.autoscale }}
        variables: ${{ parameters.variables }}