jobs:
- deployment: ${{ parameters.stage }}
  displayName: ${{ parameters.stage }}
  pool:
    vmImage: 'ubuntu-latest'
  environment: ${{ parameters.environment }}
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: 'sed -i ''s/{{Name}}/${{ parameters.app }}/g'' helm/templates/*.yaml && sed -i ''s/{{Name}}/${{ parameters.app }}/g'' helm/*.yaml && sed -i ''s/{{BuildId}}/$(Build.BuildId)/g'' helm/templates/deployment.yaml && sed -i ''s/{{environment}}/$(Environment.Name)/g'' helm/templates/deployment.yaml && sed -i ''s/{{environment}}/$(Environment.Name)/g'' Dockerfile' 
            workingDirectory: '$(System.DefaultWorkingDirectory)'
        - task: HelmInstaller@0
          inputs:
            helmVersion: '3.0.0'
            checkLatestHelmVersion: false
            installKubectl: true
        - task: HelmDeploy@0
          inputs:
            command: 'package'
            chartPath: '$(System.DefaultWorkingDirectory)/helm/'
        - task: Docker@2
          inputs:
            containerRegistry: 'SaudeID-PRD Container Registry'
            repository: '$(Build.Repository.Name)'
            command: 'buildAndPush'
            Dockerfile: '**/Dockerfile'
            tags: '$(Environment.Name)-$(BuildId.BuildId)'
        - task: HelmDeploy@0
          inputs:
            connectionType: 'Kubernetes Service Connection'
            kubernetesServiceConnection: 'GCP - dev-Kubernetes'
            namespace: '${{ parameters.namespace }}'
            command: 'install'
            chartType: 'FilePath'
            chartPath: '$(System.DefaultWorkingDirectory)/helm'
            releaseName: '${{ parameters.release }}'
            waitForExecution: false
