jobs:
- deployment: ${{ parameters.stage }}
  displayName: ${{ parameters.stage }}
  pool:
    vmImage: 'ubuntu-latest'
  environment: ${{ parameters.environment }}
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: 'sed -i ''s/{{Name}}/${{ parameters.app }}/g'' helm/*/templates/*.yaml && sed -i ''s/{{Name}}/${{ parameters.app }}/g'' helm/*/*.yaml && sed -i ''s/{{BuildId}}/$(Build.BuildId)/g'' helm/*/templates/deployment.yaml && sed -i ''s/{{environment}}/$(Environment.Name)/g'' helm/*/templates/deployment.yaml && sed -i ''s/{{environment}}/$(Environment.Name)/g'' Dockerfile' 
            workingDirectory: '$(System.DefaultWorkingDirectory)'
        - task: HelmInstaller@0
          inputs:
            helmVersion: '3.0.0'
            checkLatestHelmVersion: false
            installKubectl: true
        - task: HelmDeploy@0
          inputs:
            command: 'package'
            chartPath: '$(System.DefaultWorkingDirectory)/helm/$(Build.Repository.Name)'
        - task: Docker@0
          displayName: 'Build an image'
          inputs:
            azureSubscription: 'Microservices - Service Principal'
            azureContainerRegistry: ''
            dockerFile: Dockerfile
            includeLatestTag: true
            additionalImageTags: $(Environment.Name)-$(Build.BuildId)
        - task: Docker@0
          displayName: 'Push an image'
          inputs:
            azureSubscription: 'Microservices - Service Principal'
            azureContainerRegistry: ''
            action: 'Push an image'
            includeLatestTag: true
            additionalImageTags: $(Environment.Name)-$(Build.BuildId)
        - task: HelmDeploy@0
          inputs:
            connectionType: 'Azure Resource Manager'
            azureSubscription: 'Microservices - Service Principal'
            azureResourceGroup: ${{ parameters.resourcegroup }}
            kubernetesCluster: ${{ parameters.cluster }}
            useClusterAdmin: true
            namespace: ${{ parameters.namespace }}
            command: 'upgrade'
            chartType: 'FilePath'
            chartPath: '$(System.DefaultWorkingDirectory)/helm/$(Build.Repository.Name)'
            releaseName: ${{ parameters.release}}
            waitForExecution: false