jobs:
- deployment: ${{ parameters.stage }}
  displayName: ${{ parameters.stage }}
  pool:
    vmImage: 'ubuntu-latest'
  environment: ${{ parameters.environment }}
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
        - checkout: templates
        - task: Npm@1
          inputs:
            command: 'install'
            workingDir: '$(Build.Repository.Name)'
        - script: npm install
        - script: npm run build
        - script: npm install next
        - script: ls