jobs:
- deployment: ${{ parameters.stage }}
  displayName: ${{ parameters.stage }}
  pool:
    vmImage: 'ubuntu-latest'
  environment: ${{ parameters.environment }}
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
        - checkout: templates
        - task: DownloadSecureFile@1
          name: devgcptoken
          inputs:
            secureFile: 'dev-gcp_token.json'
        - task: DownloadSecureFile@1
          name: qagcptoken
          inputs:
            secureFile: 'qa-gcp_token.json'
        - task: DownloadSecureFile@1
          name: prodgcptoken
          inputs:
            secureFile: 'prod-gcp_token.json'
        - script: cp $(devgcptoken.secureFilePath) .
        - script: cp $(qagcptoken.secureFilePath) .
        - script: cp $(prodgcptoken.secureFilePath) .
        - script: mv $(Build.Repository.Name)/next.config.${{ parameters.environment }}.js $(Build.Repository.Name)/next.config.js
        - task: Npm@1
          inputs:
            command: 'install'
            verbose: true
            workingDir: $(Build.Repository.Name)
        - script: npm run build
          workingDirectory: ./$(Build.Repository.Name)
        - task: Docker@2
          inputs:
            containerRegistry: 'SaudeID-PRD Container Registry'
            repository: 'saudeid-prd/${{ parameters.namespace }}/${{ parameters.app }}'
            command: 'buildAndPush'
            Dockerfile: '**/Dockerfile'
            tags: |
              $(Environment.Name)-$(Build.BuildId)
              latest
        - task: ArchiveFiles@2
          inputs:
            rootFolderOrFile: './$(Build.Repository.Name)/out'
            includeRootFolder: true
            archiveType: 'zip'
            archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
            replaceExistingArchive: true
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'drop'
            publishLocation: 'Container'
        - script: gcloud auth activate-service-account --key-file ./$(Environment.Name)-gcp_token.json
        - task: GsutilRunner@0
          inputs:
            command: 'cp'
            arguments: '-r ./$(Build.Repository.Name)/out/* gs://${{ parameters.bucket }}'