jobs:
- deployment: ${{ parameters.stage }}
  displayName: ${{ parameters.stage }}
  pool:
    vmImage: 'ubuntu-latest'
  environment: ${{ parameters.environment }}
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
        - checkout: templates
        - task: DownloadSecureFile@1
          name: gcptoken
          inputs:
            secureFile: 'gcp_token.json'
        - script: cp $(gcptoken.secureFilePath) .
        - script: npm install
          workingDirectory: ./$(Build.Repository.Name)
        - script: npm run build
          workingDirectory: ./$(Build.Repository.Name)
        - task: ArchiveFiles@2
          inputs:
            rootFolderOrFile: './$(Build.Repository.Name)/out'
            includeRootFolder: true
            archiveType: 'zip'
            archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
            replaceExistingArchive: true
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'drop'
            publishLocation: 'Container'
        - script: gcloud auth activate-service-account --key-file ./gcp_token.json
        - task: GsutilRunner@0
          inputs:
            command: 'cp'
            arguments: '-r ./$(Build.Repository.Name)/out gs://{{ parameters.bucket }}'