apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{environment}}-{{Name}}
spec:
  schedule: {{crontime}}
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            # disable istio on the pod due to this issue:
            # https://github.com/istio/istio/issues/11659
            sidecar.istio.io/inject: "false"
        spec:
          containers:
          - name: {{environment}}-{{Name}}
            image: gcr.io/saudeid-prd/{{namespace}}/{{Name}}:{{environment}}-{{BuildId}}
            imagePullPolicy: Always
          restartPolicy: Never