# Repo: templates/
# File: azure-pipelines.yml

resources:
  repositories:
    - repository: templates
      type: git
      name: Area-Engenharia/templates
      ref: refs/heads/release

stages:
- stage: Development
  condition: contains(variables['Build.SourceBranch'], 'refs/heads/dev')
  jobs:
  - template: BuildTemplates/cronjob.yaml@templates
    parameters:
        namespace: 'bizdev'
        release: 'dev-job-trackco-get-nps'
        stage: 'Development'
        environment: 'dev'
        app: 'job-trackco-get-nps'
        cronjob: \"5 * * * *"
- stage: Quality
  condition: or(contains(variables['Build.SourceBranch'], 'refs/heads/release'), contains(variables['Build.SourceBranch'], 'refs/heads/hotfix'))
  jobs:
  - template: BuildTemplates/cronjob.yaml@templates
    parameters:
        namespace: 'bizdev'
        release: 'qa-job-trackco-get-nps'
        stage: 'Quality'
        environment: 'qa'
        app: 'job-trackco-get-nps'
        cronjob: \"0 1 * * *"
- stage: Production
  condition: or(contains(variables['Build.SourceBranch'], 'refs/heads/release'), contains(variables['Build.SourceBranch'], 'refs/heads/hotfix'))
  jobs:
  - template: BuildTemplates/cronjob.yaml@templates
    parameters:
        namespace: 'bizdev'
        release: 'prod-job-trackco-get-nps'
        stage: 'Production'
        environment: 'prod'
        app: 'job-trackco-get-nps'
        cronjob: \"0 1 * * *"