apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "teste-helm.environment" . }}-{{ include "teste-helm.name" . }}
  namespace: {{ include "teste-helm.namespace" . }}
spec:
  host: {{ include "teste-helm.environment" . }}-{{ include "teste-helm.name" . }}
  trafficPolicy:
    outlierDetection:
      consecutiveErrors: 7
      interval: 30s
      baseEjectionTime: 30s