apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "teste-helm.environment" . }}-{{ include "teste-helm.name" . }}-gateway
  namespace: {{ include "teste-helm.namespace" . }}
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"