apiVersion: v1
kind: Service
metadata:
  name: {{environment}}{{Name}}
  namespace: {{namespace}}
  labels:
    app: {{environment}}-{{Name}}
spec:
  ports:
  - port: 3001
    name: http
  selector:
    app: {{environment}}-{{Name}}
  type: ClusterIP
