apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{environment}}-{{Name}}-gateway
  namespace: {{namespace}}
spec:
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*'
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: saudeid-selfsigned-credential
      mode: SIMPLE