apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{environment}}-{{Name}}
spec:
  schedule: {{crontime}}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{environment}}-{{Name}}
            image: gcr.io/saudeid-prd/b2c/{{Name}}:{{environment}}-{{BuildId}}
            imagePullPolicy: Always
          restartPolicy: OnFailure